import type { Config } from 'tailwindcss';
import { C } from './shared/constants/colors';

const config: Config = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './modules/**/*.{js,jsx,ts,tsx}',
    './shared/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'jungle-deep':  C.jungleDeep,
        'jungle-mid':   C.jungleMid,
        'yellow-green': C.yellowGreen,
        gold:           C.gold,
        amber:          C.amber,
        'amber-light':  C.amberLight,
        terra:          C.terra,
        'brown-red':    C.brownRed,
        blush:          C.blush,
        cream:          C.cream,
        'cream-2':      C.cream2,
        ink:            C.ink,
        'ink-2':        C.ink2,
        muted:          C.muted,
        olive:          C.olive,
      },
      fontFamily: {
        sans:      ['PlusJakartaSans_400Regular'],
        medium:    ['PlusJakartaSans_500Medium'],
        semibold:  ['PlusJakartaSans_600SemiBold'],
        bold:      ['PlusJakartaSans_700Bold'],
        extrabold: ['PlusJakartaSans_800ExtraBold'],
      },
      fontSize: {
        '2xs':      ['11px', { lineHeight: '16px', letterSpacing: '0px' }],
        xs:         ['12px', { lineHeight: '16px' }],
        sm:         ['13px', { lineHeight: '18px' }],
        base:       ['14px', { lineHeight: '20px' }],
        'base-plus':['14.5px', { lineHeight: '21px' }],
        md:         ['15px', { lineHeight: '22px' }],
        lg:         ['16px', { lineHeight: '24px' }],
        xl:         ['18px', { lineHeight: '26px' }],
        '2xl':      ['20px', { lineHeight: '28px' }],
        '3xl':      ['22px', { lineHeight: '30px' }],
        '4xl':      ['24px', { lineHeight: '32px' }],
        '5xl':      ['26px', { lineHeight: '34px' }],
        '6xl':      ['28px', { lineHeight: '36px' }],
        '7xl':      ['30px', { lineHeight: '38px' }],
        '8xl':      ['32px', { lineHeight: '40px' }],
        '9xl':      ['34px', { lineHeight: '42px' }],
        '10xl':     ['40px', { lineHeight: '48px' }],
      },
      letterSpacing: {
        tightest: '-0.68px',
        tighter:  '-0.5px',
        tight:    '-0.26px',
        snug:     '-0.1px',
        normal:   '0px',
        wide:     '0.1px',
        wider:    '0.5px',
        widest:   '1.3px',
      },
      lineHeight: {
        snug:  '18px',
        tight: '20px',
        base:  '21px',
        lg:    '22px',
        xl:    '24px',
        '2xl': '28px',
        '3xl': '32px',
        '4xl': '40px',
      },
      borderRadius: {
        none:    '0px',
        sm:      '4px',
        DEFAULT: '8px',
        md:      '11px',
        lg:      '14px',
        xl:      '18px',
        '2xl':   '22px',
        '3xl':   '26px',
        '4xl':   '28px',
        '5xl':   '32px',
        full:    '9999px',
      },
      spacing: {
        px:  '1px',
        0:   '0px',
        0.5: '2px',
        1:   '4px',
        1.5: '6px',
        2:   '8px',
        2.5: '10px',
        3:   '12px',
        3.5: '14px',
        4:   '16px',
        5:   '20px',
        6:   '24px',
        7:   '28px',
        8:   '32px',
        9:   '36px',
        10:  '40px',
        11:  '44px',
        12:  '48px',
        14:  '56px',
        16:  '64px',
        20:  '80px',
        24:  '96px',
        28:  '112px',
        32:  '128px',
      },
    },
  },
  plugins: [],
};

export default config;
